satisfaction_general_homepage:
    path:     /
    defaults: { _controller: SatisfactionGeneralBundle:Default:index }
satisfaction_form_home:
    path:     /
    defaults: { _controller: SatisfactionGeneralBundle:Default:index }
