# app/config/routing.yml
satisfaction_form:
    resource: "@SatisfactionFormBundle/Resources/config/routing.yml"
    prefix:   /
satisfaction_general:
    resource: "@SatisfactionGeneralBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"