satisfaction_mailer:
    resource: "@SatisfactionMailerBundle/Resources/config/routing.yml"
    prefix:   /
satisfaction_crawler:
    resource: "@SatisfactionCrawlerBundle/Resources/config/routing.yml"
    prefix:   /
# app/config/routing.yml
satisfaction_form:
    resource: "@SatisfactionFormBundle/Resources/config/routing.yml"
    prefix:   /
satisfaction_general:
    resource: "@SatisfactionGeneralBundle/Resources/config/routing.yml"
    prefix:   /
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
lightsaml_sp:
    resource: "@LightSamlSpBundle/Resources/config/routing.yml"
    prefix: saml
logout:
    path: /logout
login_check:
    path: /saml/login_check
    defaults: { _controller: GeneralBundle:Default:index }