# app/config/security.yml
security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        main:
            light_saml_sp:
                provider: db_provider       # user provider name configured in step 9
                user_creator: user_creator  # name of the user creator service created in step 10
                login_path: /saml/login
                check_path: /saml/login_check
            logout:
                path: /logout
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mail/$, role: ROLE_USER }
        - { path: ^/crawler/$, role: ROLE_USER }
        - { path: ^/home$, role: ROLE_USER }
        - { path: ^/form$, role: ROLE_USER }
        - { path: ^/form/view/, role: ROLE_USER }
        - { path: ^/form/edit/, role: ROLE_USER }
        - { path: ^/form/new/, role: ROLE_USER }
        - { path: ^/$, role: ROLE_USER }