Satisfaction\FormBundle\Entity\Ticket:
  type: entity
  repositoryClass: Satisfaction\FormBundle\Entity\TicketRepository
  table: returns
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    numticket:
      type: integer
      length: 99
      nullable: false
    email:
      type: string
      length: 99
      nullable: false
    status:
      type: string
      length: 10
      nullable: false
    conformite:
      type: integer
      length: 2
      nullable: true
    delais:
      type: integer
      length: 2
      nullable: true
    accompagnement:
      type: integer
      length: 2
      nullable: true
    satisfaction:
      type: integer
      length: 2
      nullable: true
    sujet:
      type: text
      nullable: false
    description:
      type: text
      nullable: false
    commentaires:
      type: text
      nullable: true
    week:
      type: integer
      length: 2
      nullable: false
    year:
      type: integer
      length: 4
      nullable: false
    month:
      type: integer
      length: 2
      nullable: false
    first_send:
      type: datetime
      nullable: false
    second_send:
      type: datetime
      nullable: true